apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld
spec:
  selector:
    matchLabels:
      app: helloworld
  replicas: 1
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
      - name: helloworld
        image: francisconp/helloworld
        volumeMounts:
          - name: nfslocal
            mountPath: /data
      nodeSelector:
        arch: amd64
      volumes:
        - name: nfslocal
          persistentVolumeClaim:
            claimName: nfs-pvc
