apiVersion: v1
kind: Pod
metadata:
  name: helloworld
spec:
  containers:
  - name: helloworld01
    image: francisconp/helloworld
    env:
    - name: default_port
      value: '8081'
    - name: default_label
      value: 'docker.dock'
    volumeMounts:
    - mountPath: /var/run/docker.sock
      name: docker-sock
    securityContext:
      privileged: true

  volumes:
  - name: docker-sock
    hostPath:
      path: /var/run/docker.sock
      type: File