apiVersion: v1
kind: Pod
metadata:
  name: helloworld
spec:
  containers:
  - name: helloworld01
    image: francisconp/helloworld
    env:
    - name: default_port
      value: '8081'
    - name: default_label
      value: 'PV'
    volumeMounts:
    - mountPath: /data
      name: pvc01
  volumes:
    - name: pvc01
      persistentVolumeClaim:
        claimName: pvc01
