apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv 
spec:
  storageClassName: nfs-pv
  capacity:
    storage: 50Gi 
  accessModes:
    - ReadWriteMany 
  persistentVolumeReclaimPolicy: Retain 
  nfs: 
    path: /shared_directory
    server: nfsserver
    readOnly: false
